lanl/phoebus

inputs/tov.pin, src/monopole_gr/monopole_gr.cpp, src/monopole_gr/monopole_gr.hpp, src/monopole_gr/monopole_gr_interface.hpp, src/monopole_gr/monopole_gr_utils.hpp, src/phoebus_driver.cpp
As we discussed, we currently use lagged variables (i.e., from one subcycle behind) to source the monopole solver. We decided that a totally un-lagged procedure is, at the moment, not desirable. These changes are intended to lend a bit more confidence to our current approach.
I add two features that should add confidence:
1. I add a time step control that demands the time step be shorter than `dtfac * alpha/(dalpha/dt)`, which provides an approximate characteristic time scale for metric evolution. There's no stability criterion here... But presumably if we are taking time steps larger than the metric evolution time scale, then lagging our variables is certainly wrong.
2. I add a new task to the task list for the monopole solver that tries to estimate how good first-order operator …
=> Add timestep controls to the monopole gravity solver

src/fluid/tmunu.hpp, src/pgen/torus.cpp
…Bsq calc in tmunu and torus
What it says on the can. The issue is that the density is already normalized when the vector potential is computed. Dividing by an additional factor of `rho_rmax` shrinks `A` and, thanks to the `-0.2` in the definition, kills `A`, and thus `B`, at the edges of the torus.
=> fix B-field normalization in torus pgen

src/geometry/cached_system.hpp, src/geometry/geometry.cpp, src/geometry/geometry_utils.hpp, src/geometry/modified_system.hpp
This is based on a discussion with @jdolence about what geometry objects we actually need to access and from where. The geometry cache, especially the metric derivatives, take up a lot of memory. I am currently storing all geometry objects at all cell centers, faces, and nodes. However, we only really need metric derivatives at cell centers (for source terms) and the nodes are totally untouched.
This PR removes node-centered variables entirely, except for "physical coordinate locations," which is useful for 3D visualization tools like visit. It also removes metric derivatives from cell faces. This reduces the memory footprint of the caching machinery substantially... by a bit more than a factor of 2.
The price, of course, is that metric derivatives---which are needed to compute the …
=> reduce geometry memory footprint

inputs/torus.pin, scripts/movie_torus.py, scripts/plot_torus.py, scripts/python/plot_snap2d.py, src/pgen/torus.cpp, src/phoebus_utils/relativity_utils.hpp
What it says on the can. This was required to get the torus to look more like the one we're all used to. There's a switch in the problem generator to use one or the other. I also made several quality of life changes:
1. I changed the problem modifier to set up the grid exactly as bhlight does by default. This moves the inner boundary further into the horizon. The problem modifier now reports what it changed x1min and x1max to, as well as what the inner radius is.
2. I wrote some routines to calculate b^2 in `relativity_utils.hpp`
3. I added a routine to calculate the beta used for normalization via the minimum value or the old HARM style. The problem generator now reports both values.
4. I changed the default inner and outer radii of the torus in the input deck to match the standard …
=> Change default normalization of B-field in torus to the HARM-style normalization

inputs/linear_modes.pin, inputs/spherical_shock_tube.pin, inputs/torus.pin, src/CMakeLists.txt, src/geometry/cached_system.hpp, src/pgen/check_cached_geom.cpp, src/pgen/pgen.hpp
In my on-going quest to build the geometry machinery up to the ability to do on-grid computations for e.g., `MonopoleCart`, in this PR I introduce the ability to compute metric derivatives via finite differences on the grid when using cached geometry.
I allow a given geometry to specify whether or not it should do this when cached via the `geometry/do_fd_on_grid` `param`. If this `param` is not set, the cached geometry will read it in from the input deck.
The finite differences themselves are computed as centered differences where the cell-centered value is set by the differences across faces. This is vastly simplified by PR #101, which removed the metric derivatives at faces and nodes.
I add a new problem generator to be able to test this machinery, though it is not integrated into …
=>  Add the ability to compute metric derivatives by finite differences on the grid

inputs/spherical_shock_tube.pin, src/CMakeLists.txt, src/geometry/analytic_system.hpp, src/geometry/cached_system.hpp, src/pgen/check_cached_geom.cpp, src/phoebus_utils/grid_utils.hpp, src/phoebus_utils/interpolation.hpp, src/phoebus_utils/phoebus_interpolation.hpp, tst/unit/geometry/CMakeLists.txt, tst/unit/radiation/CMakeLists.txt
This is the final piece needed before I embark on Cartesian Monopole. This introduces the ability in the cached coordinate system to compute values off of cell centers/faces via interpolation, rather than falling back to the underlying analytic formulae. For particles this could be significantly cheaper, and it is necessary when gradients are computed by finite differences on the grid.
I enhanced my `check_cached_geom` problem generator to also check interpolations and checked against spherical Kerr-Schild and FLRW coordinates, and things seem to converge nicely.
One word of warning: coordinate singularities, such as at the poles, appear to cause problems (unsurprisingly)---the method still converges, but the convergence degrade as you move towards the singularity. Caution should be taken …
=> Provide interpolation for Cached Geometry

src/geometry/cached_system.hpp, src/pgen/check_cached_geom.cpp, src/phoebus_utils/phoebus_interpolation.hpp
In #111 @brryan pointed out that the cached geometry interpolation segfaults when in 1D because the interpolation operator tries to access invalid memory. This PR resolves the issue by introducing a 1D linear interpolation object. Also, rather than checking for axisymmetry, we now simply check the number of dimensions in the geometry pack. If `GetDim(3) < 2`, then we're axisymmetric If `GetDim(2) < 2`, then we're 1D.
I am still testing, but this is ready for review. @brryan can you try it to see if it resolves your issue?
=> check for lower-dimensions in interpolation. Resolves #111

cmake/Geometry.cmake, inputs/blast_wave.pin, inputs/bondi.pin, inputs/mhd_shocktube.pin, inputs/rhs_tester.pin, inputs/spherical_shock_tube.pin, inputs/torus.pin, inputs/torus_cutout.pin, inputs/tov.pin, inputs/tov_cart.pin, scripts/python/movie2d.py, src/CMakeLists.txt, src/fixup/fixup.hpp, src/fluid/fluid.cpp, src/geometry/cached_system.hpp, src/geometry/modified_system.hpp, src/geometry/monopole.cpp, src/geometry/monopole.hpp, src/geometry/sph2cart.cpp, src/geometry/sph2cart.hpp, src/main.cpp, src/monopole_gr/interp_3d_to_1d.hpp, src/phoebus_boundaries/phoebus_boundaries.cpp, src/phoebus_boundaries/phoebus_boundaries.hpp, src/phoebus_utils/history.hpp, src/tov/tov.cpp
This PR finally rewrites the Cartesian monopole coordinate system tied to the monopole GR solver. I do the following:
1. Extend `ModifiedSystem` to support geometries with a time-dependent component. The coordinate transformation is assumed to be time-independent, but the geometry itself is allowed to evolve. This basically entails computing the `d/dt` components of the metric gradients and transforming them into the new coordinate system as appropriate, assuming zero cross-talk between the space and time components of the metric. Note this approach **only** works because the coordinate transform is time-independent.
2. Write a `SphericalToCartesian` transformation object, which I use in the `monopole_gr` interpolation from the 3d grid to the 1d grid to transform relevant quantities like …
=> MonopoleCart rewrite

src/fluid/fluid.cpp
If `PHOEBUS_FLUX_AND_SRC_DIAGS` was `ON` but the fluid was not `active`, there was a memory error trying to store the fluid fluxes because they weren't being allocated.
=> Don't output flux div for fluid if fluid isnt active

src/fixup/fixup.cpp, src/fluid/con2prim_robust.hpp, src/fluid/fluid.cpp
The switch to using `user` BCs for the X2 BCs as well as the X1 BCs didn't loop the change through fix flux -- this PR fixes that. Also, `EPS` ~ 1.e-15 is now `SMALL` ~ 1.e-300 in a debug check in `con2prim_robust` -- we don't want our pressures to be restricted to > 1.e-15. This broke the torus in debug mode, for example.
=> Fix flux fixup for X2 BCs

src/phoebus_driver.cpp, src/phoebus_package.cpp
Given the segfaults happening due to `PostInitializationCommunication`, I'm adding a runtime option to disable it. Adds an input parameter in the `phoebus` block.
In the long term, we need to pull #118 through. Alternatively, changes upstream in Parthenon may make this driver stage unnecessary. @brryan what are your thoughts?
=> add an input option to short-circuit post-init-comms

src/geometry/fmks.cpp
Adds horizon radius and prograde/retrograde ISCO radii to `Params/geometry` output -- see Issue  #126.
=> Blb/issue126 - Add horizon radii and ISCO radii to output

src/fixup/fixup.cpp, src/microphysics/opac_phoebus/opac_phoebus.cpp, src/microphysics/opac_phoebus/opac_phoebus.hpp
I recently broke the GRMHD torus in my #134 PR. This PR fixes that, by providing a default `Opacities()` object in params if radiation is disabled.
=> Fix GRMHD torus

scripts/python/phoedf.py, src/microphysics/opac_phoebus/opac_phoebus.cpp
I noticed that when running outside of `scale_free` mode with radiation, the mean opacities are incorrect. This is because the mean opacity constructors expect an opacity *without* a unit conversion, e.g. `Gray`, whereas in phoebus outside of `scale_free` mode we pass in e.g. `NonCGSUnits<Gray>`.
My solution, to store both CGS and non-CGS host opacities, is a bit yucky. I wonder if this further motivates a `singularity-opac` refactor to deal also with the issue of too many variants brought up by @Yurlungur previously.
=> Mean opacity constructors expect CGS unit opacities, not NonCGSUnits<>!

src/analysis/history.cpp, src/analysis/history.hpp, src/analysis/history_utils.hpp, src/fluid/fluid.cpp, src/geometry/geometry.cpp
This PR adds the jet EM energy and momentum flux to the history output. Below, energy flux (first) and momentum flux (second). There are a couple of minor tweaks to the mass accretion rate, removal of an unused variable, etc.
=> Add jet energy and momentum flux to history

src/analysis/history.cpp, src/analysis/history.hpp, src/analysis/history_utils.hpp, src/geometry/geometry.cpp
Here I add the magnetic flux Phi to the output. Below shows the unnormalized and normalized magnetic flux. The scales seem okay but it's hard for me to compare directly to the plots in the EHT code comparison paper because they do 3D and the dynamics are a bit different. Thoughts?
=> Add magnetic flux Phi to history

src/fluid/fluid.cpp, src/microphysics/eos_phoebus/eos_phoebus.cpp, src/phoebus_driver.cpp, tst/phoebus_unit_test_main.cpp
Upon updating parthenon, @brryan found that Phoebus was crashing when restriction was called. The issue turned out to be a subtle interaction between `Metadata` and the custom prolongation/restriction operations. Essentially primitive  and/or conserved variables need to be set for prolongation/restriction when they are used for boundary conditions. However, they were being set with an "empty" prolongation/restriction operator and the code was crashing when the stored functor was a `nullptr`.
This was happening because because `Metadata::FillGhost` was being set after the constructor for the metadata object was called, but the default prolongation/restriction ops are currently only set when `Metadata` is constructed. 
I fix this issue here by creating `Metadata` objects once and not …
=> Fix restriction bug on initialization

src/radiation/monte_carlo.cpp, src/radiation/radiation.hpp
We were calling `LinearInterpLog` inside the `while ()` of a `do {} while ()` loop in the Monte Carlo sampling, and for some reason on device (power9 for me) this generates a segfault when the `dNdlnu` `ParArrayND<Real>` is passed to that inline function, either as a copy or a const reference. Don't know why that is, but the simple fix is to write out the interpolation routine in the actual `par_for`. 
This runs the `thincooling.pin` problem to completion though I didn't check the output for accuracy.
=> Fix MC issue

src/pgen/thin_cooling.cpp, src/radiation/cooling_function.cpp, src/radiation/monte_carlo.cpp, src/radiation/radiation.hpp
This PR adds a function `LeptonSign` to `radiation.hpp` to return the lepton number based on radiation type. This has been incorporated into `monte_carlo` and `cooling_function` for the `Gye` updates.
`wgtC` is scaled by the time unit so that it can be compared to values computed in nubhlight (this was needed for the `leptoneq` problem). It's a temporary fix until it can be dynamically computed. 
I also modified the thin cooling setup to set the electron fraction based on the radiation type.
Output from the `leptoneq` problem (color axis is 100(ye - 0.225)).
=> Add LeptonSign functionality

CMakeLists.txt, inputs/torus.pin, src/CMakeLists.txt, src/microphysics/eos_phoebus/eos_phoebus.cpp, src/pgen/torus.cpp, src/phoebus_utils/adiabats.hpp, src/phoebus_utils/root_find.hpp, src/phoebus_utils/unit_conversions.cpp, src/phoebus_utils/unit_conversions.hpp, tst/CMakeLists.txt, tst/unit/phoebus_utils/CMakeLists.txt, tst/unit/phoebus_utils/test_adiabats.cpp
This PR adds necessary functionality to get the torus problem working with StellarCollapse EoS.
I add the following functionalities:
- `adiabats.hpp` which includes necessary functions to compute adiabats from the table given S, Ye.
- A unit test for this has been added.
- In the torus pgen, I pull in the various quantities needed (adiabatic S, Ye, table bounds). The calculations for `rho` and `u` are replaced by `GetStateFromEnthalpy` which returns `rho` and `u` for either the ideal gas or stellar collapse EoS.
Misc change: bug found in `root_find` where `status` was not passed through correctly and it complained when the root find failed even when status was passed in.
- @brryan When you have time, can you verify that this change does not break things for your applications? (Note: You …
=> Get torus working with nuclear EoS

src/phoebus_boundaries/phoebus_boundaries.cpp, src/phoebus_boundaries/phoebus_boundaries.hpp, src/radiation/monte_carlo.cpp
This PR adds a few fixes / enhancements for monte carlo
- More support for swarm user boundaries, needed for torus's BCs.
- Add the Ucon0 term for monte carlo absorption Ye update
- Bug fix in the monte_carlo boundary bit, add in `swarm->ResetCommunication();` to stop strange crash.
=> Boundary & misc fixes for MC

src/phoebus_driver.cpp, src/phoebus_driver.hpp
Some recent changes to parthenon added more flexible RK integrators for general tableaus. Phoebus assumes low storage integrators, so this PR updates parthenon to latest (needed for particle IO) and changes `StagedIntegrator` -> `LowStorageIntegrator` as the general staged integrator doesn't support `integrator->beta` etc.
=> Use LowStorageIntegrator

inputs/torus.pin, scripts/bash/format.sh, scripts/python/phoedf.py, scripts/python/plot_torus.py, src/geometry/fmks.cpp, src/geometry/mckinney_gammie_ryan.cpp, src/geometry/mckinney_gammie_ryan.hpp, tst/unit/geometry/test_geometry.cpp
An alternative (going back to ~Tchekhovskoy+ 2011) to having an outer boundary near a disk is to use hyperexponential coordinates such that, beyond some break radius, zones grow radially in size very rapidly with radius.
This PR implements the hyperexponential coordinates based on how they are implemented in KHARMA.
=> Hyperexponential coordinates

src/phoebus_driver.cpp, src/radiation/monte_carlo.cpp, src/radiation/radiation.cpp
This is ongoing work to port the `wgtC` resolution controls in from nubhlight. I have added `ComputeTotalEmissivity` which (ideally) does just that, and `SetWeight` which uses that to set `wgtC`. Currently, `ComputeTotalEmissivity` is called in `UpdateParticleResolution` and `SetWeight` in UpdateTuningParameters'. However, it's crashing when trying to run the thermalization problem (i.e., `leptoneq`). Would appreciate eyes on this.
=> WIP: wgtC resolution controls

scripts/python/plot_torus_3d.py, src/radiation/monte_carlo.cpp
`src/radiation/monte_carlo.cpp` wasn't compiling on Chicoma GPUs; #175 had some `KOKKOS_INLINE_FUNCTION` decorators around host code. This PR removes these, and also adds `rlim` as a runtime parameter to `plot_torus_3d.py`
=> Fix GPU compilation for Monte Carlo

src/geometry/geometry.cpp
When I wrote the history stuff to compute e.g., mass accretion rate and magnetic flux, I checked that we did indeed `do_hydro` .... but not that we are doing MHD. This caused the torus problem without MHD to crash. This should fix that.
=> Small history fix for FMKS without MHD

src/phoebus_driver.cpp, src/phoebus_utils/relativity_utils.hpp, src/radiation/cooling_function.cpp, src/radiation/radiation.cpp, src/radiation/radiation.hpp
=> refactoring LightBulb_functions

CMakeLists.txt, src/CMakeLists.txt, src/microphysics/eos_phoebus/eos_phoebus.cpp, src/microphysics/eos_phoebus/eos_phoebus.hpp, src/monopole_gr/monopole_gr_base.hpp, src/pgen/progenitor.cpp, src/pgen/torus.cpp, src/phoebus_utils/adiabats.hpp, src/phoebus_utils/phoebus_interpolation.hpp, src/progenitor/progenitordata.cpp, tst/unit/geometry/CMakeLists.txt, tst/unit/monopole_gr/CMakeLists.txt, tst/unit/phoebus_utils/CMakeLists.txt, tst/unit/phoebus_utils/test_adiabats.cpp, tst/unit/radiation/CMakeLists.txt
This is only tested locally on my machine. @AstroBarker @mari2895 please check it works everywhere relevant, e.g., Chicoma.
Also, I currently point the `singularity-eos` submodule at [this branch](https://github.com/lanl/singularity-eos/pull/340). It needs to be updated once that PR goes through.
=> Update singularity-eos and singularity-opac

src/fixup/fixup.cpp, src/fixup/fixup_c2p.cpp, src/fixup/fixup_radc2p.cpp, src/fixup/fixup_src.cpp, src/phoebus_driver.cpp, src/radiation/moments.cpp, src/radiation/moments_source.cpp
New task rewrite changes in Parthenon (PR #987) required to update Phoebus accordingly. TaskStatus::fail is replaced with TaskStatus::complete. AddRegionalDependencies were replaced with TaskQualifier::local_sync.
=> updated phoebus based on recent tasking rewrite changes in parthenon (PR #987 in parthenon)

src/pgen/advection.cpp, src/pgen/torus.cpp, src/radiation/mocmc.cpp, src/radiation/monte_carlo.cpp
Small PR, updates `parthenon` to current [develop](https://github.com/parthenon-hpc-lab/parthenon/tree/3225612e267456e5731f80c594d45e6457274c3f) which includes updates to the swarm `AddEmptyParticles` API.
Only needed changes in a few places, and the `advection` tracer and `thin_cooling` monte carlo tests run. Checked on darwin.
=> Pull in Parthenon swarm refactor

src/fluid/fluid.cpp, src/phoebus_driver.cpp, src/phoebus_utils/variables.hpp
=> entropy added in outputs

src/CMakeLists.txt, src/analysis/analysis.cpp, src/analysis/analysis.hpp, src/fluid/fluid.cpp, src/phoebus_driver.cpp, src/phoebus_utils/variables.hpp
added output for entropy at z=0
=> central entropy output added

src/fixup/fixup.cpp, src/fixup/fixup.hpp, src/fixup/fixup_c2p.cpp, src/fixup/fixup_radc2p.cpp, src/fixup/fixup_src.cpp, src/fluid/con2prim_robust.hpp, src/fluid/fluid.cpp, src/fluid/fluid.hpp, src/fluid/riemann.hpp, src/microphysics/eos_phoebus/eos_phoebus.cpp, src/pgen/torus.cpp, src/phoebus_driver.cpp, src/radiation/moments_source.cpp
This PR adds knowledge of eos bounds to the floors. Specifically, for tabulated EOS, demand that the floors do not extrapolate off of the table. This required making the `bounds` param mutable.
Currently, for ideal gas, the option to enforce user set bounds is supported by supplying, e.g., `<eos>/rho_min` in the input deck. If unspecified, reasonable defaults are set.
Also fixed a misc bug in the `UserWorkBeforeOutput` code where a package and param were pulled out inside a device kernel that caused a crash on device.
=> Add eos information to floors, misc UserWorkBeforeOutput fix

src/analysis/analysis.cpp, src/analysis/history.cpp, src/analysis/history.hpp, src/progenitor/progenitordata.cpp
=> calculating Mass accretion rate for SN post-processing

src/analysis/history.cpp, src/radiation/cooling_function.cpp
Was assuming spherical geometry in heating.
=> bug in cooling function and potential bug in history.cpp

src/geometry/mckinney_gammie_ryan.hpp, src/microphysics/eos_phoebus/eos_phoebus.cpp, src/pgen/pgen.cpp, src/pgen/pgen.hpp, src/pgen/sedov.cpp
This PR incorporates changes I needed to make to run on Frontier, plus some misc fixes:
- Update `singularity-eos` to main
- Move `energy_from_rho_P` from `pgen.cpp` into the header file.
- The `mckinnie_gammie_ryan` constructor had a bug in a variable name
- `eos_phoebus.cpp` had an incorrect redefinition of the `lambda` array that the compiler interpreted as an out of bounds array access
- In the sedov pgen, the boolean to use spherical coords was loaded from input with `GetOrAddReal`
=> Run on Frontier: update singularity, relocatable device code, misc fixes

doc/sphinx/src/tracers.rst, src/phoebus_driver.cpp, src/tracers/tracers.cpp
An error that slipped in through #229: `defrag_frac` for the tracer swarms defrag routines was set to an int, but should be double/Real. This is fixed. Thanks, @Yurlungur
=> Trivial, fix: defrag_frac for tracers routines should not be int

src/fixup/fixup_netfield.cpp
When MPI is disabled, the parthenon reducers infrastructure provides MPI names. However, these are hidden in the parthenon namespace. This MR pulls out the namespace so fixup/fixup_netfield compiles when MPI is disabled. Thanks @xevra for the fix.
=> [trivial] fix fixup no mpi build
